### ISSUE TITLE
why not contribute to awesome-redux repo?

### ISSUE THREAD

**Issue by vyorkin** [markerikson/react-redux-links#11]
just asking, because there is already an existing one https://github.com/xgrommx/awesome-redux

**Comment by markerikson** [comment]
Multiple reasons:

* Awesome-Redux is a ton of links, with not much organization or distinction.  In fact, when the author submitted it to Sindre Sorhus's "Awesome Awesome" repo, the PR was rejected because Awesome-Redux was too hard to read ( https://github.com/sindresorhus/awesome/pull/348 )
* Awesome-Redux has links to boilerplates, tutorials, articles, middleware, utility libs, integration with other frameworks, and a whole bunch more.  That's all nice, but I wanted a repo that was focused on tutorials and learning.
* I also wanted a place to share the stuff that _I_ specifically feel is high-quality and worth reading

**Comment by vyorkin** [comment]
thank you for your clear explanation
