### ISSUE TITLE
Add "Gatsby-Starter-TypeScript-Redux-TDD-BDD" Somewhere?

### ISSUE THREAD

**Issue by JimLynchCodes** [markerikson/react-redux-links#126]
Hello!

Thanks so much for creating this awesome repo of information! My team and I have recently released a Gatsby React starter template that comes with Redux out of the box.

The template is all about TDD (test-driven development) and BDD (behavior-driven development). In the README it specifically calls out the quote unquote _proper_ way of dealing with async events such as API calls by putting them in "Redux middlewares", and in the scaffold we provide a simple middleware with Jest unit tests to provide an example for users and help start them off on the right foot.

Here's the project:
https://github.com/Evaluates2/Gatsby-Starter-TypeScript-Redux-TDD-BDD

Anyway, we'd love to get feedback on this project from @markerikson and everyone else in the @react + @redux community! 🙏❤️

Also, I wasn't sure exactly where something like this would fit best in the list here so I'm looking for suggestions on that as well. Thanks!

**Comment by JimLynchCodes** [comment]
bump 🙃

**Comment by markerikson** [comment]
Hey.  Appreciate the PR, but I don't think this is something I want to add.  While this list does have a "Boilerplates" section, that's largely because when I first started it, CRA hadn't been created yet, Next.js and Gatsby didn't exist either, and most folks were starting projects by cloning an existing boilerplate.

Today, my standard advice would be "use CRA with a specific template, or follow the instructions for Next to set up a project".  I don't see a need to link further boilerplates here, and really that page should be cleaned up at this point.

**Comment by JimLynchCodes** [comment]
@markerikson well that's a very strange and unexpected response! 😆

Do you really think people should setup redux, typescript, redux-localstorage, cypress + cucumber, jest with testing libraries, and setup TDD package.json scripts again and again in every project??!

Starter templates are excellent, and having the mentality that they should never be used imo leads to extremely closed-minded and inefficient teams.
